links:
  "ASCII recipes": "/"
  "Kelley": "https://klve.nl"
  "Tim Holman's morphing effect": "https://tholman.com/post/ascii-morph/"
  "WIP": "https://github.com/kelleyvanevert/asciirecip.es"
  "Fira Code": "https://github.com/tonsky/FiraCode"
